import { ControllerPaths } from '../ControllerPaths/ControllerPaths';
export const GETALLROLEREFERENCEPERMISSIONTYPEBYNAME = ControllerPaths.ROLEREFERENCEPERMISSIONTYPE + '/referencetype';
export const GETALLROLEREFERENCEPERMISSIONTYPE = ControllerPaths.ROLEREFERENCEPERMISSIONTYPE + '/getall';
export const SAVEROLEREFERENCEPERMISSIONTYPE = ControllerPaths.ROLEREFERENCEPERMISSIONTYPE + '/save';
export const UPDATEROLEREFERENCEPERMISSIONTYPE = ControllerPaths.ROLEREFERENCEPERMISSIONTYPE + '/update';
export const DELETEROLEREFERENCEPERMISSIONTYPE = ControllerPaths.ROLEREFERENCEPERMISSIONTYPE;
export const GETROLEREFERENCEPERMISSIONTYPEBYID= ControllerPaths.ROLEREFERENCEPERMISSIONTYPE;
export const FETCHALLROLEREFERENCEPERMISSIONTYPE= ControllerPaths.ROLEREFERENCEPERMISSIONTYPE +'/fetchall';
