export enum ControllerPaths {
  ROLEMENUITEMS = '/roleMenuItem',
  MENUITEMS = '/menu/item',
  MENU = '/menu',
  ROLE = '/role',
  PROJECT = '/project',
  STORE = '/store',
  STOREINCHARGE = '/storeIncharge',
  USER = '/user',
  ITEMCATEGORY = '/itemcategory',
  BLOCK = '/block',
  COMMON_REFERENCE_TYPE = '/commonreferencedetails/types',
  INDENT = '/indent',
  INDENT_ITEM = '/indent/item',
  ITEMSUBCATEGORY = '/itemsubcategory',
  ITEMSPECIFICATION = '/itemSpecification',
  ITEMUNIT = '/itemUnit',
  WORKFLOWTYPE = '/workflowtype',
  WORKFLOWSTAGE = '/workflowstage',
  LEVEL = '/level',
  UNIT = '/unit',
  HOLIDAY = '/holiday',
  WORKFLOWSERVICE = '/workflowservice',
  UNITTYPE = '/unit/type',
  COMMONREFERENCETYPE = '/commonreferencetype',
  ROLEREFERENCEPERMISSIONTYPE = '/role-permissions',
  COMMONREFERENCEDETAILS = '/commonreferencedetails',
  LEAVEREQUEST = '/leaverequest',
  WEEKOFF = '/weekoff',
  NOTIFICATION = '/notifications',
  STAGE = '/stage',
  PAYMENTPLAN = '/paymentplan',
  CLIENTINVOICEREPORTDATA = 'clientinvoicereportdata',
  REPORT_FIELDS = '/report/fields',
  EXCEL_MAPPING = '/excelmapping',
  Employee = '/employee',
  EmployeeBankingDetails = '/employeeBankDetails',
  ASSETS = '/assets',
  ASSETALLOCATION = '/assetallocation',
  QR = 'QR',
  QRTRANSACTIONDATA = 'qrtransaction',
  QRGENERATOR = 'facility',
  SECURITYPATROL = 'securitypatrol',
  SCHEDULETIME = 'scheduletime',
  ORGANIZATION = 'organization',
  REPORTS = '/reports',
  INVOICE = 'invoicereport',
  INVOICEREPORT = 'taxinvoice',
  QUOTATION = '/quotation',
  QUOTATION_CHARGE = '/charges',
  QUOTATIONITEM = '/quotation/item',
  CUSTOMER = '/customer',
  ISSUES = '/issues',
  ADDRESS = '/address',
  QRREPORT = 'qrreport',
  CUSTOMERCONSUMPTION = 'consumption',
  FACILITYSERVICES = 'facilityservices',
  AGNACUSTOMERCONSUMPTION = 'facilityInvoiceReport',
  BOOKING = '/booking',
  CLIENT = '/client',
  SALETEAM = '/sales/team',
  CLIENTINVOICEREPORT = 'monthlyClientInvoiceReport',
  LOGENTRY = '/logentry',
  DUPLICATELEADHISTORY = 'DUPLICATELEADHISTORY',
  PRIMEACTIVITYCODE = 'primeactivitycode',
  SERVICEGROUP = 'servicegroup',
  SERVICECODE = 'servicecode',
  ACCOUNTENTRY = '/accountentry',
  ACCOUNTAUDITLOG = '/accountauditlog',
  ATTENDANCE = '/attendance',
  SHIFTATTENDANCE = '/shiftBasedAttendance',
  DOCUMENTS = '/documents',
  Notifications = '/notifications',
  ADDITIONALSHIFT = '/additionalshift',
  FINGERPRINTUSERMAPPING = '/fingerprintusermapping',
  EMPLOYEEBANKDETAILS = '/employeeBankDetails',
  SALESAGGREMENTTEMPLATE = '/salesaggrementtemplate',
  SALESAGGREMENTTEMPLATEFIELDS = '/salesAgreementTemplateFields',
  GENERATESALESAGGREMENT = '/generateSalesAgreement',
  MULTILOGIN = '/multilogin',
  CACHE = '/cache',
  CUSTOMERLEGALDOCUMENT = '/customerlegaldocument',
  PROJECTDETAILS = '/projectdetails',

  INVENTORY_RECEIVABLE = '/inventoryreceivables',
  INVENTORY_RECEIVABLE_HISTORY = '/inventoryreceivable/history',
  INVENTORY_RECEIVABLE_ITEM = '/inventoryreceivable/items',
  INVENTORY_RECEIVABLE_STAGE = '/api/inventory-receivable-stage',
  STORE_INVENTORY = '/store/inventory',
  INVENTORY_TRANSFER = '/inventorytransfer',

  QUOTATION_ITEM = '/quotation/item',
  COMMON_REFERENCE_KEY = '/commonreferencedetails/mob',
  FEILDOFFICER_PATROL = '/fieldOfficerPatrol',
  DELETE_FEILDOFFICER_PATROL = '/',
}

export enum PresalesControllerPaths {
  LEADS = '/lead',
  LEAD_SOURCE = '/leadsource',
  LEADSUBSOURCE = '/leadsubsource',
  PROJECT_SALES_TEAM = '/usermanage',
  ROLE_MANAGE = '/rolemanage',
  COMMON_REFERNCE_DETAILS = '/commonreferencedetails',
  LEAD_FOLLOWUP = '/followup',
  CHANNEL_PARTNER = '/cp/register',
  SCHEDULE_VISIT = '/schedule/visit',
  DUPLICATE_LEADS = '/duplicate/lead',
  SITE_VISIT = '/site/visit',
  LEAD_BUDGET = '/leadbudget',
  TEAM_LEADS_DATA = '/lead/team/data',
  LEAD_DETAILS = '/lead/details',
  ALL_LEADS = '/lead/leads',
  LEAD_REPORT = '/lead/report',
  GET_LEAD_REPORT = '/lead/reports',
  GET_PROJECT_TEAM_REPORT = '/lead/project/team',
  GET_BOOKED_COUNT = '/lead/team/bookingcount',
  TOTAL_LEADS = '/totalleads',
  CHANNEL_PATNER_DASHBOARD_COUNT = '/lead/dashboard/count',
  EOI = '/eoi',
  MCUBE_AUDIO = '/mcubeaudio',
  FACEBOOK_LEADS = '/facebookleads',
  MCUBE = '/mcube',
}

export enum ProcurementControllerPaths {
  PURCHASE_ORDER = '/purchase/order',
  QUOTATION = '/quotation',
  DOCUMENTS = '/documents',
  QUO_TERMS_AND_COND = '/qo/terms/condition',
  STORE_INVENTORY = '/store/inventory',
}

export enum salesTeamControllerPaths {
  GETALLSALESTEAM = ControllerPaths.SALETEAM + '/project',
  FETCHAll = ControllerPaths.SALETEAM,
  SAVE = ControllerPaths.SALETEAM,
  UPDATE = ControllerPaths.SALETEAM,
  GETBYID = ControllerPaths.SALETEAM,
  DELETEBYID = ControllerPaths.SALETEAM,
}

export enum WorkOrderControllerPaths {
  PRIMEACTIVITYCODE = '/primeactivitycode',
  SERVICEGROUP = '/servicegroup',
  SERVICECODE = '/servicecode',
  SACCODE = '/saccode',
  WORKORDERHEADER = '/workorderheader',
  VENDOR = '/vendor',
  WORKORDERCREATION = '/workordercreation',
  WORKORDERQUANTITIES = '/wo/quantities',
  STANDINUSER = '/standinuser',
  WORKORDERBILLING = '/workorderbilling',
  WORKORDERBILLING_QUANTITIES = '/wob/quantities',
  WORKORDER_AMOUNT = '/workorder/amount',
  WORKORDER_GST = '/wo/gst',
  WORKORDERTERMSANDCONDITIONS = '/wo/terms/conditions',
}

export enum CRMControllerPaths {
  PROJECT_CHARGE = '/projectcharge',
  CUSTOMER_STAGE = '/customerstages',
  APPLICANT_INFO = '/applicantinfo',
  BOOKING_CHARGE = '/bookingcharges',
  PAYMENT_DETAILS = '/paymentdetails',
  CUSTOMER_PAYMENTS = '/customerpayment',
  DASH_BOARD = '/dashboard',
  CRM_DOCUMENTS = '/crm/documents',
  PROJECT_DETAILS = '/projectdetails',
  CRM_FOLLOWUP = '/crm/followup',
}
